version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:*"
      logging:
        patterns:
          - "org.apache.logging.log4j:*"
          - "com.lmax:*"
